Full Traceback (most recent call last):
  File "/opt/miniconda3/envs/snakemake/lib/python3.10/site-packages/snakemake/io.py", line 1177, in expand
    return [
  File "/opt/miniconda3/envs/snakemake/lib/python3.10/site-packages/snakemake/io.py", line 1178, in <listcomp>
    formatter.vformat(filepattern, (), comb)
  File "/opt/miniconda3/envs/snakemake/lib/python3.10/string.py", line 165, in vformat
    result, _ = self._vformat(format_string, args, kwargs, used_args, 2)
  File "/opt/miniconda3/envs/snakemake/lib/python3.10/string.py", line 205, in _vformat
    obj, arg_used = self.get_field(field_name, args, kwargs)
  File "/opt/miniconda3/envs/snakemake/lib/python3.10/string.py", line 270, in get_field
    obj = self.get_value(first, args, kwargs)
  File "/opt/miniconda3/envs/snakemake/lib/python3.10/string.py", line 227, in get_value
    return kwargs[key]
KeyError: 'library'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/envs/snakemake/lib/python3.10/site-packages/snakemake/__init__.py", line 593, in snakemake
    workflow.include(
  File "/opt/miniconda3/envs/snakemake/lib/python3.10/site-packages/snakemake/workflow.py", line 1182, in include
    exec(compile(code, snakefile.get_path_or_uri(), "exec"), self.globals)
  File "/home/jeszyman/repos/atac-seq/workflow/int_test.smk", line 33, in <module>
    expand(atac_fastq_proc + "/{library}_flex_2.fastq.gz", library_id = LIBRARIES),
  File "/opt/miniconda3/envs/snakemake/lib/python3.10/site-packages/snakemake/io.py", line 1183, in expand
    raise WildcardError("No values given for wildcard {}.".format(e))
snakemake.exceptions.WildcardError: No values given for wildcard 'library'.

WildcardError:
No values given for wildcard 'library'.
  File "/home/jeszyman/repos/atac-seq/workflow/int_test.smk", line 33, in <module>
