The flag 'directory' used in rule all is only valid for outputs, not inputs.
Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 4
Rules claiming more threads will be scaled down.
Job stats:
job           count    min threads    max threads
----------  -------  -------------  -------------
all               1              1              1
atac_index        1              1              1
total             2              1              1

Resources before job selection: {'_cores': 4, '_nodes': 9223372036854775807}
Ready jobs (1):
	atac_index
Select jobs to execute...
Selected jobs (1):
	atac_index
Resources after job selection: {'_cores': 3, '_nodes': 9223372036854775806}

[Tue Aug 30 14:43:48 2022]
rule atac_index:
    input: test/inputs/chr19.fa
    output: testref/ucsc_mm10_chr19
    log: test/logs/atac_index.log
    jobid: 5
    resources: tmpdir=/tmp


        workflow/scripts/index.sh         test/inputs/chr19.fa         testref/ucsc_mm10_chr19/ucsc_mm10_chr19         4         testref/ucsc_mm10_chr19 &> test/logs/atac_index.log
        
 singularity  exec --home /home/jeszyman/repos/atac-seq --bind /home/jeszyman:/home/jeszyman --bind /mnt:/mnt --bind /opt/miniconda3/envs/snakemake/lib/python3.9/site-packages:/mnt/snakemake /home/jeszyman/sing_containers/atac.1.1.0.sif bash -c 'workflow/scripts/index.sh         test/inputs/chr19.fa         testref/ucsc_mm10_chr19/ucsc_mm10_chr19         4         testref/ucsc_mm10_chr19 &> test/logs/atac_index.log'
Activating singularity image /home/jeszyman/sing_containers/atac.1.1.0.sif
Full Traceback (most recent call last):
  File "/opt/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2372, in run_wrapper
    run(
  File "/home/jeszyman/repos/atac-seq/workflow/atac_read_process.smk", line 71, in __rule_atac_index
  File "/opt/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/shell.py", line 263, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command ' singularity  exec --home /home/jeszyman/repos/atac-seq --bind /home/jeszyman:/home/jeszyman --bind /mnt:/mnt --bind /opt/miniconda3/envs/snakemake/lib/python3.9/site-packages:/mnt/snakemake /home/jeszyman/sing_containers/atac.1.1.0.sif bash -c 'workflow/scripts/index.sh         test/inputs/chr19.fa         testref/ucsc_mm10_chr19/ucsc_mm10_chr19         4         testref/ucsc_mm10_chr19 &> test/logs/atac_index.log'' returned non-zero exit status 1.

[Tue Aug 30 14:43:49 2022]
Error in rule atac_index:
    jobid: 5
    output: testref/ucsc_mm10_chr19
    log: test/logs/atac_index.log (check log file(s) for error message)
    shell:
        
        workflow/scripts/index.sh         test/inputs/chr19.fa         testref/ucsc_mm10_chr19/ucsc_mm10_chr19         4         testref/ucsc_mm10_chr19 &> test/logs/atac_index.log
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Full Traceback (most recent call last):
  File "/opt/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2372, in run_wrapper
    run(
  File "/home/jeszyman/repos/atac-seq/workflow/atac_read_process.smk", line 71, in __rule_atac_index
  File "/opt/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/shell.py", line 263, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command ' singularity  exec --home /home/jeszyman/repos/atac-seq --bind /home/jeszyman:/home/jeszyman --bind /mnt:/mnt --bind /opt/miniconda3/envs/snakemake/lib/python3.9/site-packages:/mnt/snakemake /home/jeszyman/sing_containers/atac.1.1.0.sif bash -c 'workflow/scripts/index.sh         test/inputs/chr19.fa         testref/ucsc_mm10_chr19/ucsc_mm10_chr19         4         testref/ucsc_mm10_chr19 &> test/logs/atac_index.log'' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 592, in _callback
    raise ex
  File "/opt/miniconda3/envs/snakemake/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 578, in cached_or_run
    run_func(*args)
  File "/opt/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2405, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in line 33 of /home/jeszyman/repos/atac-seq/workflow/atac_read_process.smk:
Command ' singularity  exec --home /home/jeszyman/repos/atac-seq --bind /home/jeszyman:/home/jeszyman --bind /mnt:/mnt --bind /opt/miniconda3/envs/snakemake/lib/python3.9/site-packages:/mnt/snakemake /home/jeszyman/sing_containers/atac.1.1.0.sif bash -c 'workflow/scripts/index.sh         test/inputs/chr19.fa         testref/ucsc_mm10_chr19/ucsc_mm10_chr19         4         testref/ucsc_mm10_chr19 &> test/logs/atac_index.log'' returned non-zero exit status 1.
  File "/home/jeszyman/repos/atac-seq/workflow/atac_read_process.smk", line 33, in __rule_atac_index

RuleException:
CalledProcessError in line 33 of /home/jeszyman/repos/atac-seq/workflow/atac_read_process.smk:
Command ' singularity  exec --home /home/jeszyman/repos/atac-seq --bind /home/jeszyman:/home/jeszyman --bind /mnt:/mnt --bind /opt/miniconda3/envs/snakemake/lib/python3.9/site-packages:/mnt/snakemake /home/jeszyman/sing_containers/atac.1.1.0.sif bash -c 'workflow/scripts/index.sh         test/inputs/chr19.fa         testref/ucsc_mm10_chr19/ucsc_mm10_chr19         4         testref/ucsc_mm10_chr19 &> test/logs/atac_index.log'' returned non-zero exit status 1.
  File "/home/jeszyman/repos/atac-seq/workflow/atac_read_process.smk", line 33, in __rule_atac_index
  File "/opt/miniconda3/envs/snakemake/lib/python3.9/concurrent/futures/thread.py", line 52, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/jeszyman/repos/atac-seq/.snakemake/log/2022-08-30T144348.510909.snakemake.log
unlocking
removing lock
removing lock
removed all locks
