Full Traceback (most recent call last):
  File "/opt/miniconda3/envs/snakemake/lib/python3.10/site-packages/snakemake/__init__.py", line 593, in snakemake
    workflow.include(
  File "/opt/miniconda3/envs/snakemake/lib/python3.10/site-packages/snakemake/workflow.py", line 1182, in include
    exec(compile(code, snakefile.get_path_or_uri(), "exec"), self.globals)
  File "/home/jeszyman/repos/atac-seq/workflow/int_test.smk", line 100, in <module>
  File "/opt/miniconda3/envs/snakemake/lib/python3.10/site-packages/snakemake/workflow.py", line 1182, in include
    exec(compile(code, snakefile.get_path_or_uri(), "exec"), self.globals)
  File "/home/jeszyman/repos/atac-seq/workflow/atac.smk", line 462, in <module>
  File "/opt/miniconda3/envs/snakemake/lib/python3.10/site-packages/snakemake/workflow.py", line 1309, in rule
    name = self.add_rule(
  File "/opt/miniconda3/envs/snakemake/lib/python3.10/site-packages/snakemake/workflow.py", line 461, in add_rule
    raise CreateRuleException(
snakemake.exceptions.CreateRuleException: The name fastqc is already used by another rule

CreateRuleException:
The name fastqc is already used by another rule
  File "/home/jeszyman/repos/atac-seq/workflow/int_test.smk", line 100, in <module>
  File "/home/jeszyman/repos/atac-seq/workflow/atac.smk", line 462, in <module>
